# Generated by Django 3.2.18 on 2023-04-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.IntegerField(choices=[(0, 'All Recipes'), (1, 'Vegan'), (2, 'Chocolate Recipes'), (3, 'Fruits'), (4, 'Gluten Free'), (5, 'Birthday and Wedding'), (6, 'Christmas Recipes')], default=0),
        ),
    ]
