# Generated by Django 3.2.18 on 2023-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230410_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('all', 'All Recipes'), ('vegan', 'Vegan'), ('chocolate', 'Chocolate Recipes'), ('fruits', 'Fruits'), ('gluten_free', 'Gluten Free'), ('birthday_wedding', 'Birthday and Wedding'), ('christmas', 'Christmas Recipes')], default='all', max_length=20),
        ),
    ]
