# Generated by Django 3.2.18 on 2023-04-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('All Recipes', 'All Recipes'), ('Vegan', 'Vegan'), ('Chocolate Recipes', 'Chocolate Recipes'), ('Fruits', 'Fruits'), ('Gluten Free', 'Gluten Free'), ('Birthday & Wedding', 'Birthday & Wedding'), ('Christmas Recipes', 'Christmas Recipes')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dificulty',
            field=models.CharField(choices=[('Easy', 'easy'), ('Medium', 'medium'), ('Hard', 'hard')], default='Easy', max_length=10),
        ),
    ]
