# Generated by Django 3.2.18 on 2023-04-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230413_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='body',
        ),
    ]
