# Generated by Django 3.2.18 on 2023-04-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230413_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
